[package]
name = "verbug"
version = "0.1.0"
authors = ["Michael Zimmermann <sigmaepsilon92@gmail.com>"]
edition = "2018"

[dependencies]
blas-src = { version = "*", features = ["openblas"] }
openblas-src = { version = "*", features = ["static"] }
ndarray-linalg = "0.12"